[package]
name = "lib_annex"
version = "0.1.0"
authors = ["Jason Goldberger <jlgoldb2@asu.edu>"]
edition = "2018"

[dependencies]
rand = "0.6"
ndarray = "0.12.1"
ndarray-rand = "0.9.0"
num-traits = "0.2.6"

